project_name: agent-cli
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: agent

archives:
  - files:
    - LICENSE
    wrap_in_directory: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "Release {{ .Tag }}"
